name: validate
on:
  pull_request:
    branches: [main]
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup go
        uses: actions/setup-go@v4
        with:
          go-version: '>=1.20.1'
          cache: true

      - name: test
        run: make test

      - name: check license headers
        run: make checklicense

      - name: build
        run: make build
